### ISSUE TITLE
Page formatting on Level Solutions page

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/rapid-router#1060]
**Describe the bug**
The styling on https://www.codeforlife.education/teach/solutions_navigation/ seems to have gone wrong; level text is misaligned with purple tab headers.

**To Reproduce**
Go to https://www.codeforlife.education/teach/solutions_navigation/

**Expected behaviour**
I would expect this page to look nicer with the purple tab headers deep enough to fit the Level x-y text in it

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/0f1cae56-1a77-45f5-9c02-8987b704fa30)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context**

**Comment by sebp999** [comment]
I tried to reproduce on Windows 10 and  Chrome v 89.0.4389.128 without success.  Also Ubuntu 20.04 and Chromium Version 89.0.4389.114 
![Screenshot 2021-04-15 092231.png](https://images.zenhubusercontent.com/5dd165e72de56b0001c54603/c7bf1c68-f1c2-4008-80d7-ea0280dadd66)

**Comment by sebp999** [comment]
Reproduced! Mac OS 11.5.1, Chrome 92

**Comment by sebp999** [comment]
Actually I could reproduce on public server but not on localhost server.  Comparing the html between the two, I think the problem is fixed already:  on local server I get blocks like this for the accordion elements

```
               <h3 id="episode10">
                <div>
                    Introduction to Python
                    <span class="episode_range_text">
                        Levels 80-91
                    </span>
                </div>
                </h3>
```

But on the public server there is no "Introduction to Python" text

                ```
<h3 id="episode10">
                <div>
                    
                    <span class="episode_range_text">
                        Levels 80-91
                    </span>
                </div>
                </h3>
                <div>

```

Adding the "introduction to Python" using developer tools fixes it.

Therefore I think this issue is already fixed but the fix has not been deployed yet.

**Comment by dionizh** [comment]
Per our chat, it looks like maybe there’s an if else somewhere that causes the Introduction to Python text to not appear. I don’t think the problem is fixed, as nobody has worked on this recently.

**Comment by sebp999** [comment]
I'm afraid I can't work this out without seeing the production database but here are some notes that might help.  

I know that the issue is coming from the missing variable   in the template at https://github.com/ocadotechnology/codeforlife-portal/blob/8bd382a08c2796b9f9a390fccee6c4220dd668f3/portal/templates/portal/teach/teacher_level_solutions.html#L52 .  This data is fetched from the database here https://github.com/ocadotechnology/codeforlife-portal/blob/8bd382a08c2796b9f9a390fccee6c4220dd668f3/portal/views/teacher/solutions_level_selector.py#L52 and there is no conditional logic there or in the template.  

As far as I can tell, the only differences between my machine and the server is the type of database and the contents of the database. I'm going to leave it parked but I would have a look at the production database next, and see if the name of the episode is set?

**Comment by sebp999** [comment]
Just to be clear, the reason why I think this might be a database problem is that I can reproduce this with exact formatting by replacing the episode names with "", and I don't think that an episode's name is ever displayed anywhere else.

**Comment by dionizh** [comment]
Thank you for the investigation @sebp999. This page is now removed as we think teachers can just use the Solve button to see the solutions.
