### ISSUE TITLE
Cannot save a custom level

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1158]
**Describe the bug**
Users can't save level when creating a new level

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'level creator and create level'
2. Click on 'character' You will see that no character is selected. Leave as this.
3. Scroll down to 'save level'

**Expected behaviour**
It should allow saving, but because no character is auto-selected, the user gets an error. We think we should autoselect the van.

**Screenshots**
![Screenshot 2021-01-25 at 10.54.53.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/a1e01ba4-043c-4fb7-bd8f-10debf813e5e)

**Comment by sebp999** [comment]
I haven't been able to reproduce this

Steps:
Log in as a teacher or as a student in Chrome (incognito):

- /rapidrouter/ click `create`
- /rapidrouter/level_editor/#
- Choose character on the left: It is a van by default.
https://images.zenhubusercontent.com/18399425/744bfa4f-bb4e-4246-b7d3-9010e425b571/screencast_2021_02_05_15_48_41.mp4

**Comment by sebp999** [comment]
(after more discussion with Florian) -  I can't reproduce the error with a fresh database and no cookies, but people can with existing state.  When a teacher works on a level and logs out, then another teacher logs in, the level grid is as the last teacher left it ie it persists in the browser not the session.  That is because Blockly is storing its state in the browser's local storage:
![Screenshot from 2021-02-08 09-18-58.png](https://images.zenhubusercontent.com/5dd165e72de56b0001c54603/1f6d63d8-b268-40f6-9cab-34013fec5eea)
Therefore one theory is that when you load up blockly and your browser already has a state in local storage, the character is not saved there for some reason.  Needs more investigation.

**Comment by faucomte97** [comment]
@sebp999 it looks like this error is related to this issue - either it's the cause or a byproduct. Could be worth investigating.

![Selection_264.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/f016d603-1880-4dab-b6fc-905af3825cb3)

![Selection_265.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/08a3ca8f-99bb-49bb-aefe-45163e736c1c)

Let me know if you want the link to the actual logs.

**Comment by sebp999** [comment]
https://github.com/ocadotechnology/rapid-router/pull/1170 probably solves this
