### ISSUE TITLE
Update hint text on If/Else block

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1183]
![Screenshot 2021-05-25 at 14.05.39.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/052aa22d-cbda-44b7-8429-344fdf3c8118)

1. Mouseover text on cog when closed: _Click cog to see options_
2. Mouseover text on dialogue box when open: _Drag the blocks on the left to sit under the block on the right then click the cog to close._

**Comment by dionizh** [comment]
@lauracumming We can only update existing tooltips, not adding new ones. So the four tooltips are:
- Mouseover on the initial block "if do"
- Mouseover on the left of the help window "else if"
- Mouseover on the left of the help window "else"
- Mouseover on the right of the help window "if"

On the other hand, we can update so there's separation between the left and the right hand side of the help window so it's clearer that you drag from the left to the right: (Notice that the panel of the blocks turn light grey too, because they use the same style)

<img width="712" alt="Screenshot 2021-06-16 at 13 59 47" src="https://user-images.githubusercontent.com/4784791/122224746-5161e900-ceac-11eb-8d43-ff7de6d1c7d7.png">

**Comment by faucomte97** [comment]
@dionizh did you manage to fix the grey background issue? I see that the blocks of the left side have a grey background now like they should have!

**Comment by dionizh** [comment]
@faucomte97 Yes 🙂, just confirming first if that's what we want.
