### ISSUE TITLE
Remove superfluous Python commands in Rapid Router

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/rapid-router#1520]
## Task Description
Rebecca has given feedback that students are confused by the provision of superfluous commands in the Py commands modal. 
She has suggested it would be better to only show what is needed for each level.

The Py commands modal can be found in any Python-based level in Rapid Router: levels 92-109, 113-115, 119-122.
It is in the top-right corner of the Python Program window.

![Screenshot from 2023-12-11 18-27-49](https://github.com/ocadotechnology/rapid-router/assets/33633200/0f4e1229-7c7a-4d52-956a-9c5b12ced758)

## Acceptance Criteria
- [ ] Update the Py commands modal so it dynamically shows the Py commands that are relevant to the specific level, instead of consistently showing all the Py commands.
- [ ] There is no concept in the code of "level-specific commands", therefore this task requires an implementation of this. Once this mapping has been implemented, then the content of the modal can be pulled in.

**Comment by shahid-25-khalid** [comment]
Does this task still need completing? Happy to give it a go if suitable? :)

**Comment by lauracumming** [comment]
Yes it does please.

**Comment by lauracumming** [comment]
@faucomte97

**Comment by faucomte97** [comment]
Hi @shahid-25-khalid,

Yes, as Laura said this task is still relevant and you are more than welcome to have a go at it 😄 

Let me know if the task description is clear enough. Feel free to ask any questions too!

Thanks

**Comment by shahid-25-khalid** [comment]
This is great, I will have a go at this issue. 

@faucomte97 I can't remember how to open a branch or clone repository of the rapid router code, and how to search for the specific part. Could someone show me this again briefly please? I remember Kamil showed me before how to open the games code in VS Code and then search for the specific issue segment, but I have forgotten how to do this. I am quite free for a zoom call this week or next.

Thanks,
Shahid.

**Comment by faucomte97** [comment]
Hi @shahid-25-khalid,

[Our docs here](https://docs.codeforlife.education/developer-guide/development-guidelines) outline how to get started, including how to fork a repo and create a branch 🙂 

Let me know how you get on following these docs.

Thanks,

Florian

**Comment by shahid-25-khalid** [comment]
Hi @faucomte97,

Thanks for sharing this. And no problem, I'll have a crack at this and let you know how I get on.

Thanks again,

Catch up soon,
Shahid.

**Comment by shahid-25-khalid** [comment]
Just an update, I am still working on this project, just setting up my local fork repository for testing. Will update on my progress in a couple weeks time :)

**Comment by faucomte97** [comment]
No worries! Thanks for the update :D

**Comment by Ridwanah** [comment]
Hi, I have picked up on this task.

**Comment by Ridwanah** [comment]
Hi, I have a working implementation of this. I just need to download chromedriver and run the selenium tests to make sure its working properly.

**Comment by faucomte97** [comment]
Hi @Ridwanah, that is awesome news!

We have actually been struggling to get the Dev Container setup in VS Code to work with the Chromedriver and Selenium in order to run the tests locally - but there are a few options:

- I have recently tried to add the Chromedriver feature to the Dev Container so the tests can be run fine from within the container, but I've only partially succeeded. You can check out my ongoing PR if you'd like: https://github.com/ocadotechnology/rapid-router/pull/1653

As far as I remember, I was able to get the tests to run **in headless mode**, meaning I had to copy over the headless chromedriver options to the `default` driver in `rapid_router_test_settings.py` so that `pytest` would run Selenium in headless mode. You can have a look and see if you can get the tests to run that way, but I appreciate it's not a very fun task to work on.

- Alternatively, you could either rely on the pipeline to test your code. Once you open your PR, our Github Actions will automatically run the tests against your code so it should tell you if your tests are passing or not.

Let me know how you get on, and if you need any more information on this.

**Comment by Ridwanah** [comment]
Hi, 
I plan to open a pull request as I haven't been able to get the selenium tests working.

**Comment by faucomte97** [comment]
Hi @Ridwanah, 

Have a look at the comment I wrote on your pull request - you just need to open a pull request to our rapid-router repo instead of the workspace repo. Once that's done successfully, the tests workflow can be triggered.

**Comment by Ridwanah** [comment]
Hi,
I opened a PR for rapid-router and I was able to get the tests running. It failed 3 tests so I am working on fixing them.

**Comment by Ridwanah** [comment]
Hi, I made a new commit to fix the errors but I am not sure how to get the tests running a second time. I checked the pull request and the new commit is there.

**Comment by faucomte97** [comment]
Hi @Ridwanah, I've just re-approved the pipeline run so the tests should start running again now.

**Comment by faucomte97** [comment]
I've also updated your branch so it took the latest changes from `master`, so make sure to pull those changes in your IDE when you next go to your local branch

**Comment by faucomte97** [comment]
One more thing - we have a flaky test which fails occasionally, it's the test about saving and loading a workspace - if that test fails I normally just rerun the tests.

**Comment by faucomte97** [comment]
LGTM

**Comment by lauracumming** [comment]
LGTM

**Comment by lauracumming** [comment]
need a related task for level editor
