### ISSUE TITLE
Level 75 solution

### ISSUE THREAD

**Issue by CheriePun** [ocadotechnology/rapid-router#638]
Found a shorter solution for level 75.
In both his solution and the solution in teaching pack did not use the limited block repeat-n-times, was that there to guide users to use repeat-until instead?

![capture](https://cloud.githubusercontent.com/assets/11837539/9653083/d489dc96-5218-11e5-9545-33ec078a5a77.PNG)

**Comment by Spycho** [comment]
To be addressed once teaching materials have been shifted to web generated content.

**Comment by davidnmbond** [comment]
My daughter asked why her solution scored 8/10 for algorithm for RapidRouter 75.  I stared at it and couldn't answer and so Googled and found this post.

This is a bug.  Please fix!

**Comment by Spycho** [comment]
Hi @davidnmbond. We found that the solution in the teaching materials scores 10/10. The issue here is that we score attempts based on matching the target solution as per the teaching materials, and in this case, the solution in the teaching materials is actually not the best solution. So we incorrectly mark down a better solution. To address this, we need to change the target solution, which means changing the teaching materials, which is currently awkward as they are in PDFs rather than web generated content. So we were planning on making this change after we change the teaching materials to be web generated content rather than PDFs.

In the meantime, take a look at http://storage.googleapis.com/codeforlife-assets/python/program_solutions/UKS2-PST-Program-Solutions-Table.pdf to find out what our (not the best) target solution is for level 75.

**Comment by MasterWolfScar** [comment]
Does anybody know how to get 20/20 on Code for Life Level 27: Farmyard

**Comment by mrniket** [comment]
@MasterWolfScar our github issues are for bugs and feature requests. Please contact codeforlife@ocado.com and we should be able to help you directly :)

As for this issue, we checked the current solution and this one is still better so we should update the level 75 solution in the game and the teaching packs. This issue is still relevant.

**Comment by sebp999** [comment]
I think this is caused by #1123 so I am replacing the model solution with the new shorter model
