### ISSUE TITLE
Disable saving and loading of workspace when user is not logged in

### ISSUE THREAD

**Issue by pawelkrupinski** [ocadotechnology/rapid-router#677]
Rationale: At the moment we store workspace to browser's local storage, which can cause confusion to the users, since it's not portable and can be lost.
Disable the loading and saving of workspace when the user is not logged in.
Options:
- Hide Load / Save buttons when the user is not logged in
- Display popup with a warning when user tries to load or save while not being logged in

**Comment by CelineBoudier** [comment]
For the moment, it's only half working, so the best thing is indeed to deactivate this feature for not logged-in users at least until we get UX advice - and maybe prompt them to register as @Spycho suggested.

**Comment by mrniket** [comment]
Still an issue

**Comment by faucomte97** [comment]
Still relevant - we should not be saving the workspace unless logged in.

**Comment by sebp999** [comment]
Have made a PR: https://github.com/ocadotechnology/rapid-router/pull/1216 .  This change does 2 things: 

1. disable browser local storage when the user is not logged in, so that a user can play some levels and pass computer to another user who will not be stuck with friend's progress.  
2. disable save and load buttons in game page if the user is not logged in.

**Comment by sebp999** [comment]
(NB the tests for Rapid Router are not running in CI because they depend on the change to the portal)
