### ISSUE TITLE
Add javascript translation support

### ISSUE THREAD

**Issue by mikebryant** [ocadotechnology/rapid-router#759]

**Comment by mikebryant** [comment]
Separate catalogs for each app will be pretty simple to implement, and give us what we need

**Comment by piotrrepetowski** [comment]
Is it something you wanted to do as a part of this issue?

https://github.com/piotrrepetowski/rapid-router/commit/e8a812ee938440bd2a7e8ff31880dd66eab69c01

Probably some changes will be required in crowdin setup (since new po file is generated as a result of makemessages).

**Comment by mikebryant** [comment]
Yeh, that's the general idea.
You'll want to namespace that url though (as we should be doing in general)
e.g. `name='game/javascript-catalog'`

**Comment by piotrrepetowski** [comment]
What about rapid-router/javascript-catalog? Game seems to be too generic don't know possibly conflicting apps though.

**Comment by mikebryant** [comment]
Well, `game` is the name of the python package. It is too generic, and needs changing, but that's a fairly big task.
`rapid-router/javascript-catalog` would be fine :)

**Comment by CelineBoudier** [comment]
There is an issue about the game name https://github.com/ocadotechnology/rapid-router/issues/313
While still not fully urgent, it would be good to look into it at some point.

rapid-router/javascript-catalog sounds good to me too.

**Comment by CelineBoudier** [comment]
or rapidrouter/javascript-catalog . Anyway.

**Comment by piotrrepetowski** [comment]
It turned out that current django's javascript_catalog (gettext implementation) has a strange fallback to 'en' which stops us from using CrowdIn live mode (it works with other locales e.g. pl or en-gb). Please have a look at:
https://github.com/django/django/blob/1.8.2/django/views/i18n.py#L211
lines from 211 to 250.

More details here:
https://github.com/django/django/commit/11c60b529816c5d29c3b4145055bf59b2e389de5
https://code.djangoproject.com/ticket/26328
https://groups.google.com/forum/#!topic/django-developers/gDU8HlZg4Ug

It means that we need to either provide a locale folder for 'en' or use something without 'en' prefix as a pseudo-language.

The django's master contains a changed implementation, but it hasn't been released yet.

**Comment by mikebryant** [comment]
I don't actually see why that would affect us.. It only falls back if the language code doesn't have translations - the pseudo language does..

**Comment by mikebryant** [comment]
Oh, now I see why it breaks. That is annoying

**Comment by mikebryant** [comment]
Ok, lets change the pseudo language code to `lol` (LOLCAT)

I'll raise a PR

**Comment by piotrrepetowski** [comment]
Thanks

**Comment by piotrrepetowski** [comment]
Do you think we need anything else as a part of this request?

I think externalizing js strings can be included in #760.

**Comment by mrniket** [comment]
Stale, will track through other issues
