### ISSUE TITLE
Understand the steps to enable Cow levels and Night Mode

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/rapid-router#952]
@dionizh 22/4/22: Thinking to enable these instead of removing them.

Rapid Router code still contains a lot of references and logic to do with some features that had been started but that we never fully implemented or deployed completely. These features are the "Night Mode" and the "Cow levels".
The "Cow levels" feature's goal was to add cows that were roaming on the roads of the game and the player had to avoid them as they drove along the road.
The "Night Mode" feature's goal was to have limited vision in the levels as it was nighttime.

Any and all references to these features need to be removed as they are polluting the code quite a lot.

**Comment by mrniket** [comment]
Still relevant

**Comment by dionizh** [comment]
We're thinking that it could be fun to have the cows. @sebp999 Can you please investigate how far are we from having the full functionality? Some prototype and screenshot would be great too if you can get it working to some degree. This is more of an investigation task, so please let us know what you think will be the remaining tasks if we want to get the cows working. I'm guessing the night mode is further away, but if you could also have a look, let us know the stage of it :)

**Comment by dionizh** [comment]
Summary from @sebp999:

- You can add white cows or brown cows. 
- When you play the level, cows start off hidden and appear randomly, sometimes only when you’re about to crash into them. The cow stays in one place/square.
- You can choose to sound horn or puff up when a cow appears.  Puffing up makes the van grow bigger then shrink again, and it can then go through the cow without crashing into it.  Horn makes a noise.
- Brown cows get scared away by the horn
- White cows get scared away by puffing up. (this bit doesn’t work: the van just goes through the cow)

![Screenshot 2022-04-22 at 12 31 00](https://user-images.githubusercontent.com/4784791/165737048-b50e75fe-17fc-40aa-ba36-632711aa9ec5.png)

This possibly teachers about event handler? Because road ahead is true when there is a cow there, and you can’t add steps like “turn left” just “puff up” and “sound horn”. 

What confuses me is that the way of making the cows go away is to make two purple “event handlers” like this: on brown cow, sound horn and on white cow puff up.  So for every level you just need to remember to set up the two things and I’m not sure what the point of that is if you just need to do the same thing each time.  Is it that it is a puzzle to work out the difference between white and brown?  There’s some code that is for moving the cows around, so at some point the idea might have been that they would wander around.  But then you just need the “event handlers”.

**Comment by dionizh** [comment]
@sebp999 Thank you for all the findings. The team had a discussion about this and have decided what we want to do. It needs quite a lot of changes, so I created an epic for it here #1334. The first task is to update the usage of the cows: #1335. We can keep this thread of record/discussion, but please move on to #1335. Any questions let me know!

**Comment by sebp999** [comment]
Cow functionality in PR #1336
